#!/usr/bin/env python3
"""Generate GitHub Markdown indexes from monthly submissions."""
import argparse
from collections import defaultdict
import html
import json
import os
from pathlib import Path
import re
from urllib.parse import quote
from zoneinfo import ZoneInfo

from validate import ROOT, collect, timestamp


def text(value):
    value = html.escape(str(value), quote=False).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'([\\`*_|\[\]])', r'\\\1', value)


def link(label, target):
    return f'[{text(label)}]({quote(str(target), safe="/:#?=&%+@")})'


def generate(root=ROOT, record=False):
    config, ledger, notes = collect(root)
    if record:
        for n in notes:
            ledger.setdefault(n['id'], n['added_at'])
        (root / 'data/added_at.json').write_text(json.dumps(ledger, indent=2, sort_keys=True) + '\n')
    base = root / 'catalog'
    expected = set()

    def write(path, content):
        expected.add(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('<!-- Generated by scripts/index.py; edit monthly YAML instead. -->\n\n' + content.rstrip() + '\n', encoding='utf-8')

    def relative(source, target):
        return os.path.relpath(target, source.parent)

    def nav(path):
        targets = [('All papers', root / 'README.md')] + [(f'By {kind}', base / f'by-{kind}/README.md') for kind in ('month', 'topic')]
        return ' · '.join(link(label, relative(path, target)) for label, target in targets)

    # Canonical paper identity is global. Time indexes use its first appearance
    # across all members, so later duplicate submissions cannot add time rows.
    papers = defaultdict(list)
    for n in notes:
        papers[n['paper_id']].append(n)
    records = []
    for pid, contributions in papers.items():
        contributions.sort(key=lambda n: (timestamp(n['added_at']), n['member']))
        first = contributions[0]
        records.append(dict(first, contributions=contributions,
                            topics=sorted({t for n in contributions for t in n['topics']}),
                            month=timestamp(first['added_at']).astimezone(ZoneInfo(config['timezone'])).strftime('%Y-%m')))
    records.sort(key=lambda n: (timestamp(n['added_at']), n['paper_id']), reverse=True)
    groups = {kind: defaultdict(list) for kind in ('month', 'topic')}
    for n in records:
        groups['month'][n['month']].append(n)
        for topic in n['topics']:
            groups['topic'][topic].append(n)
    def table(path, entries, provenance=False):
        if not entries:
            return 'No papers yet.'
        rows = ['| Paper | Year / venue | Topics |' + (' Submitted by | First added |' if provenance else ''),
                '| --- | --- | --- |' + (' --- | --- |' if provenance else '')]
        for n in entries:
            topics = ', '.join(link(config['topics'][t], relative(path, base / 'by-topic/README.md') + f'#{t}') for t in n['topics'])
            members = ', '.join(link(c['member_name'], relative(path, root / c['source'])) for c in n['contributions'])
            paper = link(n['title'], n['url'])
            codes = sorted({c['code_url'] for c in n['contributions'] if c.get('code_url')})
            if codes:
                paper += ' · ' + ' / '.join(link('Code', url) for url in codes)
            added = timestamp(n['added_at']).astimezone(ZoneInfo(config['timezone'])).strftime('%Y-%m-%d')
            rows.append(f'| {paper} | {n["year"]} {text(n.get("venue", ""))} | {topics} |' + (f' {members} | {added} |' if provenance else ''))
        return '\n'.join(rows)

    home = root / 'README.md'
    intro = f'# {text(config["title"])}\n\n{nav(home)}\n\n'
    intro += link('Contribute', 'CONTRIBUTING.md') + ' · ' + link('Monthly YAML template', 'templates/monthly.yaml')
    intro += '\n\nOne file per member per month. Add or edit papers in the same file throughout the month.\n\n'
    intro += f'## All papers ({len(records)})\n\n' + table(home, records)
    write(home, intro)
    write(base / 'README.md', '# Papers\n\n' + nav(base / 'README.md'))
    for kind, grouping in groups.items():
        listing = base / f'by-{kind}/README.md'
        body = f'# By {kind}\n\n{nav(listing)}\n\n'
        keys = sorted(grouping, reverse=kind == 'month')
        for key in keys:
            if not re.fullmatch(r'[A-Za-z0-9_-]+', key):
                raise ValueError(f'Unsafe index key: {key}')
        labels = {key: config['topics'][key] if kind == 'topic' else key for key in keys}
        body += ' · '.join(link(f'{labels[key]} ({len(grouping[key])})', f'#{key}') for key in keys) + '\n\n'
        for key in keys:
            entries = sorted(grouping[key], key=lambda n: timestamp(n['added_at']), reverse=True)
            body += f'<a name="{key}"></a>\n\n## {text(labels[key])}\n\n'
            body += table(listing, entries, provenance=kind == 'month') + '\n\n'
            body += link('Back to top', f'#by-{kind}') + '\n\n'
        write(listing, body if grouping else body + 'No papers yet.\n')
    for path in base.rglob('*.md'):
        if path not in expected and path.read_text().startswith('<!-- Generated by scripts/index.py;'):
            path.unlink()
    print(f'Generated {len(expected)} pages; {len(records)} unique papers, {len(notes)} contributions.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--record', action='store_true')
    args = parser.parse_args()
    generate(record=args.record)
