#!/usr/bin/env python3
"""Generate GitHub-native Markdown indexes from weekly submissions."""
import argparse
from collections import defaultdict
import html
import os
from pathlib import Path
import re
from urllib.parse import quote

from build import ROOT, collect


def text(value):
    value = html.escape(str(value), quote=False).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'([\\`*_|\[\]])', r'\\\1', value)


def link(label, target):
    return f'[{text(label)}]({quote(str(target), safe="/:#?=&%+@")})'


def generate(root=ROOT, record=False):
    # Reuse ingestion without requiring the optional website assets.
    config, ledger, notes = collect(root)
    if record:
        import json
        for note in notes:
            if not note['example']:
                ledger.setdefault(note['id'], note['added_at'])
                note['pending'] = False
        (root / 'data/added_at.json').write_text(json.dumps(ledger, indent=2, sort_keys=True) + '\n')
    destination = root / 'catalog'
    expected = set()

    def write(path, content):
        expected.add(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('<!-- Generated by scripts/index.py; edit weekly YAML instead. -->\n\n' + content + '\n', encoding='utf-8')

    def relative(source, target):
        return os.path.relpath(target, source.parent)

    for example in (False, True):
        base = destination / 'examples' if example else destination
        active = [n for n in notes if n['example'] == example]
        groups = {kind: defaultdict(list) for kind in ('week', 'topic', 'member')}
        for n in active:
            groups['week'][n['week']].append(n)
            groups['member'][n['member']].append(n)
            for topic in n['topics']:
                groups['topic'][topic].append(n)
        if not example:
            for member in config['members']:
                groups['member'][member]
            for topic in config['topics']:
                groups['topic'][topic]
        def nav(path):
            targets = [('All papers', base / 'README.md')] + [(f'By {kind}', base / f'by-{kind}/README.md') for kind in groups]
            return ' · '.join(link(label, relative(path, target)) for label, target in targets)
        def table(path, entries):
            papers = defaultdict(list)
            for n in entries:
                papers[n['paper_id']].append(n)
            if not papers:
                return 'No papers yet.'
            rows = ['| Paper | Year / venue | Topics | Member | Added week |', '| --- | --- | --- | --- | --- |']
            for paper_notes in papers.values():
                n = paper_notes[0]
                topics = sorted({t for item in paper_notes for t in item['topics']})
                topic_links = ', '.join(link(config['topics'][t], relative(path, base / f'by-topic/{t}.md')) for t in topics)
                members = ', '.join(link(item['member_name'], relative(path, base / f'by-member/{item["member"]}.md')) for item in paper_notes)
                weeks = ', '.join(link(w, relative(path, base / f'by-week/{w}.md')) for w in sorted({item['week'] for item in paper_notes}, reverse=True))
                source = link('YAML', relative(path, root / n['source']))
                paper = link(n['title'], n['url'])
                if n.get('code_url'):
                    paper += ' · ' + link('Code', n['code_url'])
                rows.append(f'| {paper} · {source} | {n["year"]} {text(n.get("venue", ""))} | {topic_links} | {members} | {weeks} |')
            return '\n'.join(rows)
        title = 'Example papers' if example else config['title']
        index = base / 'README.md'
        content = f'# {text(title)}\n\n{nav(index)}\n\n'
        if example:
            content += '**Demo data — excluded from real contributions.**\n\n'
        content += f'{len({n["paper_id"] for n in active})} papers · {len(active)} submissions\n\n' + table(index, active)
        if not example:
            content += '\n\n' + link('Examples', 'examples/README.md') + ' · ' + link('Contribute', '../CONTRIBUTING.md')
        write(index, content)
        for kind, grouping in groups.items():
            listing = base / f'by-{kind}/README.md'
            body = f'# By {kind}\n\n{nav(listing)}\n\n'
            for key in sorted(grouping, reverse=kind == 'week'):
                if not re.fullmatch(r'[A-Za-z0-9_-]+', key):
                    raise ValueError(f'Unsafe index key: {key}')
                label = config['topics'][key] if kind == 'topic' else config['members'].get(key, 'Example reader') if kind == 'member' else key
                page = listing.parent / f'{key}.md'
                body += f'- {link(label, page.name)} ({len(grouping[key])})\n'
                write(page, f'# {text(label)}\n\n{nav(page)}\n\n' + table(page, grouping[key]))
            write(listing, body if grouping else body + 'No submissions yet.\n')
    # Remove only our obsolete generated pages, never source submissions.
    for path in destination.rglob('*.md'):
        if path not in expected and path.read_text().startswith('<!-- Generated by scripts/index.py;'):
            path.unlink()
    print(f'Generated {len(expected)} GitHub index pages.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--record', action='store_true')
    args = parser.parse_args()
    generate(record=args.record)
